- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffInspection.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/36
> Fix system ruff detection

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffInspection.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/56
> Support file path when run ruff command

- README.md
Hello!
First, I love that someone finally got around to creating integration for `ruff`. :)
This pull introduces minor touch-ups to the README.md:
* Add badge with the current number of downloads
* Fix typos and capitalization.
* Move "Sponsors" to the bottom of the page to make room for more important information at first glance (e.g. features, screenshots).
* Remove the "Settings" screenshot, as it adds nothing to the already existing information on the page.
* Made "Links" more accurate.
* Added link to the "Development" section of the documentation to the "Contributing" section in README.md to help people get started faster.
Some of those changes may be too opinionated, feel free to remove or disregard what you don't feel is right. :)
> Make README.md more friendly for a first-time user.

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/70
> Support Windows

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Closes:https://github.com/koxudaxi/ruff-pycharm-plugin/issues/36
> Support ruff command in user site

- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/82
> Support conda system path

- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/91
> Fix unexpected decode error

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffFileDocumentManagerListener.kt
- src/com/koxudaxi/ruff/RuffFixService.kt
Closes:https://github.com/koxudaxi/ruff-pycharm-plugin/issues/108
> Fix `Cannot create listener` error

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- Resolves: #123
I'd write a test but I have no idea how...
> (🐞) Force UTF-8 on Windows

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/RuffModel.kt
- src/com/koxudaxi/ruff/RuffQuickFix.kt
Related Issue:https://github.com/koxudaxi/ruff-pycharm-plugin/issues/142
> Support ruff 0.0.260

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffQuickFix.kt
Related Issues: https://github.com/koxudaxi/ruff-pycharm-plugin/pull/144
> Fix multi-edit fixes

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffFixService.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Related Issues https://github.com/koxudaxi/ruff-pycharm-plugin/issues/125
> add --force-exclude to default arguments

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffFileDocumentManagerListener.kt
- src/com/koxudaxi/ruff/RuffFixService.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/161
> Fix content vanishes when set --force-exclude

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/166
> Support Conda virtual environment

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/169
> Fix ruff executable path rollback problem

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/RuffModel.kt
- src/com/koxudaxi/ruff/RuffQuickFix.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/180
> Support one-based column indices for Edits

- build.gradle.kts
- gradle.properties
https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#incremental-compilation
kotlin.incremental.useClasspathSnapshot=false
> Support Kotlin 1.8.20

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffSuppressQuickFix.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/147
> Add suppress QuickFix

- CHANGELOG.md
- resources/META-INF/plugin.xml
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffNoqaDocumentationTarget.kt
- src/com/koxudaxi/ruff/RuffNoqaDocumentationTargetProvider.kt
- src/com/koxudaxi/ruff/RuffSuppressQuickFix.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/168
> Add inlay hint for noqa code

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/190
> Ignore toml parse error

- CHANGELOG.md
Reverts koxudaxi/ruff-pycharm-plugin#204
> Revert "Changelog update - `v0.0.17`"

- .github/workflows/build.yml
- gradle.properties
Reverts koxudaxi/ruff-pycharm-plugin#196
> Revert "Support 232 EAP"

- src/com/koxudaxi/ruff/Ruff.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/205 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/217
> Fix StringIndexOutofBoundException error

- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffNoqaDocumentationTarget.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/213
> Fix New hover on error code throws exception

- .idea/icon.svg
- resources/META-INF/pluginIcon.svg
- resolves #136
https://plugins.jetbrains.com/docs/intellij/plugin-icon-file.html#plugin-logo-requirements
> (🎁) Add icon

- README.md
- docs/index.md
- gradle.properties
- resources/META-INF/only-ultimate.xml
- resources/META-INF/plugin.xml
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigService.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffLspServerSupportProvider.kt
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
Document: https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/
> Support ruff-lsp

- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffCacheService.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffVersion.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/266
> Support --output-format

- CHANGELOG.md
- gradle.properties
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/283
> Support 2023.3 EAP

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffCacheService.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
Issues: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/295
[Ruff-0.0.26.zip](https://github.com/koxudaxi/ruff-pycharm-plugin/files/13311408/Ruff-0.0.26.zip)
> Fix async version checking

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffLspServerSupportProvider.kt
- src/com/koxudaxi/ruff/RuffNoqaDocumentationTarget.kt
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
- src/com/koxudaxi/ruff/RuffProjectInitializer.kt
Related Issues: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/308
> Fix minimum PyCharm version

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/308
> Fix conda env in Linux and macOS

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/346
> Support multiple module project

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffApplyService.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/344
> Improve Application of Ruff Results to Python Files

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/281
> Support "reformat code" partially

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/330 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/312
> Improve format process

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffPostFormatProcessor.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/pull/353
> Fix UI freeze

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/397
> Ignore lsp restart error

- CHANGELOG.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffApplyService.kt
- src/com/koxudaxi/ruff/RuffCacheService.kt
- src/com/koxudaxi/ruff/RuffVersion.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/404
> add check args

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/406
> Fix ruff executable detection

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffLspServerSupportProvider.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/358
> Improve ruff config path in wsl

- CHANGELOG.md
- README.md
- docs/index.md
- gradle.properties
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffCacheService.kt
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigService.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffLspServerSupportProvider.kt
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
- src/com/koxudaxi/ruff/RuffProjectInitializer.kt
- src/com/koxudaxi/ruff/RuffVersion.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/447
> Support new LSP integration

- .github/workflows/build.yml
- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- testSrc/com/jetbrains/python/PythonMockSdk.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/449
> Support 242 EAP

- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffNoqaDocumentationTarget.kt
> Use rule or --explain dependent on version.

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/lsp/intellij/RuffLspServerSupportProvider.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/RuffLanguageServer.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/RuffLanguageServerFactory.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/446
> Fix idea lsp server on wsl

- CHANGELOG.md
- gradle.properties
- resources/META-INF/only-lsp4ij.xml
- resources/META-INF/plugin.xml
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
- src/com/koxudaxi/ruff/RuffProjectInitializer.kt
- src/com/koxudaxi/ruff/lsp/RuffLspClient.kt
- src/com/koxudaxi/ruff/lsp/RuffLspClientManager.kt
- src/com/koxudaxi/ruff/lsp/intellij/RuffIntellijLspClient.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/RuffLsp4IntellijClient.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/490
> LSP4IJ should be optional

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
> Fix Ruff format checkbox

- CHANGELOG.md
- gradle.properties
Related Issues: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/525
> Support 243-EAP

- CHANGELOG.md
- gradle.properties
- resources/META-INF/plugin.xml
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigService.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffLoggingService.kt
- src/com/koxudaxi/ruff/RuffLoggingToolWindowFactory.kt
- src/com/koxudaxi/ruff/lsp/intellij/RuffIntellijLspClient.kt
Related Issues: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/543
> feat: ruff logging console toggle

- CHANGELOG.md
- gradle/libs.versions.toml
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffApplyService.kt
- src/com/koxudaxi/ruff/RuffAsyncFormatterFix.kt
- src/com/koxudaxi/ruff/RuffAsyncFormatterFormat.kt
- src/com/koxudaxi/ruff/RuffCacheService.kt
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigService.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffExternalAnnotator.kt
- src/com/koxudaxi/ruff/RuffFormatOnSaveAction.kt
- src/com/koxudaxi/ruff/RuffLoggingService.kt
- src/com/koxudaxi/ruff/RuffLoggingToolWindowFactory.kt
- src/com/koxudaxi/ruff/RuffPackageManagerListener.kt
- src/com/koxudaxi/ruff/RuffProjectInitializer.kt
- src/com/koxudaxi/ruff/RuffRun.kt
- src/com/koxudaxi/ruff/lsp/RuffLspClient.kt
- src/com/koxudaxi/ruff/lsp/RuffLspClientManager.kt
- src/com/koxudaxi/ruff/lsp/intellij/RuffLspServerSupportProvider.kt
- src/com/koxudaxi/ruff/lsp/intellij/supports/RuffLspCodeActionsSupport.kt
- src/com/koxudaxi/ruff/lsp/intellij/supports/RuffLspDiagnosticsSupport.kt
- src/com/koxudaxi/ruff/lsp/intellij/supports/RuffLspFormattingSupport.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/RuffLanguageServer.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/RuffLanguageServerFactory.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/features/RuffLSPCodeActionFeature.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/features/RuffLSPDiagnosticFeature.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/features/RuffLSPFormattingFeature.kt
- src/com/koxudaxi/ruff/lsp/lsp4ij/features/RuffLSPHoverFeature.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/297 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/551 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/546 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/529 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/506 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/495 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/491 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/476 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/443 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/424 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/416 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/415 https://github.com/koxudaxi/ruff-pycharm-plugin/issues/297 …
> feat: add features to lsp

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
- src/com/koxudaxi/ruff/RuffAsyncFormatter.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/546
> fix: Add support for partial formatting using --range option

- CHANGELOG.md
- gradle.properties
- gradle/libs.versions.toml
- src/com/koxudaxi/ruff/Ruff.kt
- testSrc/com/jetbrains/python/PythonMockSdk.kt
Closes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/560
> Support 251 EAP

- CHANGELOG.md
- src/com/koxudaxi/ruff/Ruff.kt
Related Isses: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/359
> fix: Fix Incorrect --stdin-filename Path Conversion for Ruff Under WSL

- CHANGELOG.md
- src/com/koxudaxi/ruff/RuffConfigPanel.form
- src/com/koxudaxi/ruff/RuffConfigPanel.kt
- src/com/koxudaxi/ruff/RuffConfigService.kt
- src/com/koxudaxi/ruff/RuffConfigurable.kt
- src/com/koxudaxi/ruff/RuffImportOptimizer.kt
Fixes: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/575
> feat: Add opt-in setting for Ruff import optimizer
